version: '3.8'

services:
  mvc:
    build:
      context: ./BrainStormEra-MVC
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  razor:
    build:
      context: ./BrainStormEra-Razor
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

  businesslogic:
    build:
      context: ./BusinessLogicLayer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  dataaccess:
    build:
      context: ./DataAccessLayer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
