version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BrainStormEra;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    restart: unless-stopped
volumes:
  mssqldata:
